### ISSUE TITLE
Order Debugger Launch

### ISSUE THREAD

**Issue by dmosites** [airswap/airswap-debugger#27]

**Comment by mikestarrdev** [comment]
- [ ] Error state: put in a check where after user submits JSON, `JSON.parse(json)` checks if JSON is valid, or decompressed order from URL checks if URL is valid
- [ ] If `contractAddress` is present in JSON or URL, have it override the Selector. Something like this: `_swapContractAddress = enteredAddress || addressFromHook`. The overridden contract address should be passed into `useDomainInfo` hook to fetch EIP721Domain info

**Comment by mikestarrdev** [comment]
Don's feedback, tasks:

`{
"chainId":11155111,
"swapContract":"0xD82E10B9A4107939e55fCCa9B53A9ede6CF2fC46",
"nonce":"1712633888155",
"expiry":"1719286688",
"signerWallet":"0xE9DA154834D8c9A8030B175EB3bFd974130AC0a0",
"signerToken":"0xf450ef4f268eaf2d3d8f9ed0354852e255a5eaef",
"signerAmount":"1000000",
"protocolFee":"5",
"senderWallet":"0x0000000000000000000000000000000000000000",
"senderToken":"0x20aaebad8c7c6ffb6fdaa5a622c399561562beea",
"senderAmount":"1000000",
"v":"28",
"r":"0x9de70c532d82bc3da353528cb698acf7e0059c4d83dc0057219b8d5754bd6343",
"s":"0x3768e0451df492a8c9faeeabb5cbc4e7eff902756f53317361dbd6693ce29b84"
}`

- [ ] Edit text field so it takes either JSON or URL. Have it detect what it is. e.g. `startsWith('http') or indexOf('http') == 0 `
- [ ] add etherscan links to contract addresses
- [ ] changing the chainId in JSON to `1` and it still reads "ready to swap"

**Comment by mikestarrdev** [comment]
Merged new changes with `main`. For now I'll close this issue, but a few cosmetic issues still need to be made.
